import { Project } from "../types/project";

const withBase = (path?: string): string | undefined => {
    if (!path) return undefined;
    if (/^(https?:)?\/\//.test(path)) return path;
    return `${import.meta.env.BASE_URL}${path.replace(/^\/+/, '')}`;
  };

export const PROJECTS: Project[] = [
    {
      id: '1',
      title: 'DualPathDx（開發中）',
      description: 'AI agent 診斷系統，旨在解決現有研究缺乏兼顧常見疾病與罕見疾病診斷系統之痛點，並確保其具有透明性、可追溯性、準確性。',
      responsibility: '獨立開發此系統',
      difficulties: '幾乎所有技術，包含設計完整系統架構、LLM、ML等等都是我原先不熟悉且在學校甚少接觸的，故花了很多努力在熟悉這些技術',
      solution: '透過網路資源、大型語言模型協助學習，並在遇到架構、方向上的問題時，向組內的學長請教',
      date: '2025/12~',
      imageUrl: withBase('assets/images/dualPathDx.png'),
      categories: ['系統開發', '校外Lab'],
      technologies: ['Python', 'LLM', 'ML'],
    },
    {
      id: '9',
      title: 'WARP',
      description: '主題為 WARP: Guaranteed Inner-Layer Repair of NLP Transformers，為 NLP Transformer 模型設計的約束型修復框架，透過凸二次規劃（QP）、將模型修復範圍擴展至內部隱藏層，以有效修正對抗性擾動所造成的預測錯誤，同時為每個修復樣本提供可證明的正確性與魯棒性保證。投稿國際頂尖會議COLM（Conference on Language Modeling）。',
      date: '2025/7 ~ 2026/3',
      visitUrl: 'https://arxiv.org/abs/2604.00938',
      competitionUrl:'https://colmweb.org/',
      responsibility: '協助開發、撰寫論文',
      difficulties: '模型修復是我之前未接觸過的領域，需從頭了解其基本概念、如何進行及閱讀相關領域論文',
      solution: '透過網路資源、每週開會學習並應用',
      imageUrl: withBase('assets/images/WARP.png'),
      categories: ['研究'],
      technologies: ['Model Repair'],
    },
    {
      id: '2',
      title: 'OpenNCCU 徵才月集點卡',
      description: 'OpenNCCU與校際活動合作，包含徵才月與聖誕市集，透過集點卡，使集點活動更透明、方便與無紙化，活躍使用者破1500人。',
      date: '2026/2 ~ 2026/3',
      visitUrl: 'https://opennccu.com/career-month',
      responsibility: '2025聖誕市集與2026徵才月，接手前人的code並更新流程、頁面與維護。',
      difficulties: '了解前人留下的code base再加以開發，並在開發時間非常短的壓力下完成開發修復錯誤並上線。',
      solution: '精進自己的能力，並在開發後與PM溝通，確保未來開發時長',
      imageUrl: withBase('assets/images/stampCard.png'),
      categories: ['網頁開發'],
      technologies: ['Vue', 'TypeScript'],
    },
    {
      id: '3',
      title: 'OpenNCCU 校園地圖',
      description: '與校園內各種活動合作，包含徵才博覽會、市集、畢業辦桌等',
      responsibility:'開發獨立地圖頁面、攤位定位功能、收藏功能、搜尋功能',
      date: '2025/2 ~ 2025/10',
      visitUrl:'https://opennccu.com/eventmap/christmas-bazaar',
      imageUrl: withBase('assets/images/eventmap.png'),
      gifUrl: withBase('assets/gif/eventmap.gif'),
      categories: ['網頁開發'],
      technologies: ['Vue', 'TypeScript'],
    },
    {
      id: '4',
      title: 'Solarlytic',
      description: '在DevJam Hackathon 時開發，最終獲得 Google Cloud 賽道第一名。Solarlytics: 陽光下的智慧決策為自助試算太陽能評估平台，旨在解決民眾在安裝屋頂太陽能時遇到的資訊不透明、難以評估與決策門檻高等問題。該平台結合 Google Cloud 技術，整合日照、地點、品牌、效率、成本等多元參數，讓使用者能夠快速評估自家安裝太陽能的適配性、投資回收期與效益，並提供多品牌比較與個人化方案建議，協助用戶做出最佳決策。',
      date: '2025/6',
      responsibility:'獨立開發前端頁面',
      difficulties:'黑客松開發時間短，需在24小時內定下主題、方向並完成開發，並與不熟悉的跨校組員一同協力完成',
      solution:'分工合作，並定時確認大家進度',
      competitionUrl: 'https://devjam.tw/',
      imageUrl: withBase('assets/images/solarlytics.png'),
      gifUrl: withBase('assets/gif/solarlytics.gif'),
      categories: ['黑客松', '網頁開發',],
      technologies: ['React'],
    },
    {
      id: '5',
      title: '撿紅點',
      description: '以數位科技強化社會安全網，串聯政府與民間，建立即時通報與協作機制，打造全民參與的安全支持系統，核心主軸為「即時安全求助」、「社區響應網」、「地理資訊整合」。',
      responsibility: '開發前端網頁、地圖路線規劃',
      difficulties: 'Handling complex real-time data synchronization across multiple clients.',
      solution: 'Implemented a robust WebSocket-based syncing layer with optimistic UI updates.',
      date: '2025/11',
      competitionUrl: withBase('https://codefest.taipei/2025-fall/'),
      imageUrl: withBase('assets/images/reddot/pic4.png'),
      gallery:[withBase('assets/images/reddot/pic1.png'), 
        withBase('assets/images/reddot/pic2.png'), 
        withBase('assets/images/reddot/pic3.png'),
        withBase('assets/images/reddot/pic4.png'),
        withBase('assets/images/reddot/pic5.png'),
        withBase('assets/images/reddot/pic6.png'),
        withBase('assets/images/reddot/pic7.png')],
      categories: ['黑客松', '網頁開發'],
      githubUrl:'https://github.com/fangyulab/codefest2025',
      technologies: ['React', 'Python'],
    },
    {
      id: '6',
      title: 'DBug: 為學生設計的錯題歸納平台',
      description: '本專案旨在解決學生族群在整理錯題時，因手動歸納題目而耗費大量精力與時間成本，進而降低學習效率的痛點，主要功能將包含：以照片的形式上傳錯題、錯題管理、練習功能與互動，打造一款去紙本化的錯題歸納系統，實現永續環保之理念，讓學生在數位時代中享受更高效、便捷且環保的學習方式。',
      responsibility:'前端架構建設與系統、錯題練習及側邊欄',
      date: '2025/6',
      githubUrl: 'https://github.com/chennaijia/113-2_DBMS',
      imageUrl: withBase('assets/images/DBug.png'),
      categories: [ '網頁開發', '系統開發', '課程專案'],
      technologies: ['Vue', 'SQL'],
    },
    {
      id: '7',
      title: 'FinDisaster',
      description: '以 Java 為開發核心的災害資訊檢索系統，強調系統的擴充性與模組化架構。該系統利用 JSoup 技術實施網頁爬蟲，並將抓取到的資料儲存在階層式網頁樹狀結構中，以利於動態提取不同來源的災害內容。其核心為結合爬蟲與關鍵字加權演算法，根據使用者定義的關鍵字精準評估資訊相關性，並自動對搜尋結果進行優先級排序與組織。',
      responsibility:'系統架構、前端、其他人也搜尋功能',
      date: '2025/6',
      imageUrl: withBase('assets/images/finDisaster_1.png'),
      gallery:[ withBase('assets/images/finDisaster_2.png')],
      gifUrl: withBase('assets/gif/finDisaster.gif'),
      githubUrl:'https://github.com/meimeielin/DS_WATB.git',
      categories: [ '系統開發', '課程專案'],
      technologies: ['Java', 'Web Scraping'],
    },
    {
      id: '8',
      title: '二手書交易平台',
      description: '二手教科書交易是大學生在學期間一定會面對的交易，現行方法卻常通過FB社團進行交易，導致資訊模糊不清、難以搜尋等缺點，為解決此痛點，在大一期末時，我使用Java架設二手書交易平台。',
      date: '2024/6',
      imageUrl: withBase('assets/images/secondhand.png'),
      gifUrl: withBase('assets/gif/secondhand.gif'),
      categories: [ '系統開發', '課程專案'],
      technologies: ['Java'],
    },
  ];